#!/bin/bash

function exit() { kill -SIGINT $$; } #$$ is the pid for the current process

export KERNEL_NAME=helios
export KERNEL_BASE=$PWD

_PATH="tools scripts"

for p in $_PATH
do
	if [[ ! -e $p ]]
	then
		echo "Please run this script from the root directory of the source."
		exit
	else
		export PATH=$KERNEL_BASE/$p:$PATH
	fi	
done

SCONSPATH=tools/scons/script

if [[ ! -e $SCONSPATH ]]
then
	git submodule init
	git submodule update
fi

export PATH=$SCONSPATH:$PATH
export PYTHONPATH=$KERNEL_BASE/tools/scons/engine:$PYTHONPATH

run(){
    qemu -cdrom $KERNEL_BASE/img/$KERNEL_NAME.iso
}

updateiso(){
	cp out/kernel rootfs/
    genisoimage -input-charset default -R -b boot/grub/stage2_eltorito -no-emul-boot -boot-load-size 4 -boot-info-table -o "$KERNEL_BASE/img/$KERNEL_NAME.iso" "$KERNEL_BASE/rootfs"
}
