import os
from os.path import join, splitext
from pprint import pprint

Import("env32 env32_ut")

#Core modules
#GC Modules
#rt

#prepare imports first

objs = []
#HACK:Replace limited depth globs with more generic versions
objs.extend(env32.Object(Glob("src/*.d")))
objs.extend(env32.Object(Glob("src/*/*.d")))
objs.extend(env32.Object(Glob("src/*/*/*.d")))
objs.extend(env32.Object(Glob("src/*/*/*/*.d")))
objs.extend(env32.Object(Glob("src/*/*/*/*/*.d")))
objs.extend(env32.Object(Glob("src/*/*/*/*/*/*.d")))


objs.extend(env32.Object(Glob("src/*.c")))
objs.extend(env32.Object(Glob("src/*/*.c")))
objs.extend(env32.Object(Glob("src/*/*/*.c")))
objs.extend(env32.Object(Glob("src/*/*/*/*.c")))
objs.extend(env32.Object(Glob("src/*/*/*/*/*.c")))
objs.extend(env32.Object(Glob("src/*/*/*/*/*/*.c")))
env32.StaticLibrary("kruntime", objs)

