import os
from os.path import join, splitext
from pprint import pprint

Import("env32 env32_ut")

#Core modules
#GC Modules
#rt

#prepare imports first

objs = []
#HACK:Replace limited depth glob with a more generic version
objs.extend(env32.Object(Glob("src/*/*/*/*/*.d")))
env32.StaticLibrary("kruntime", objs)
