import os
from os.path import join

#TARGETS
sub_projects = [
    "kruntime",
    "krt"
]

#out = []

for project in sub_projects:
     SConscript(join(project, "SConscript")
                , duplicate=0)


#Return("out")
