#!/usr/bin/python
import subprocess
import re
import shutil
from pipeline import *
import os
from os.path import join

dirStack = []

def pushd(path):
    curDir = os.getcwd()
    os.chdir(os.path.abspath(path))
    dirStack.append(os.path.abspath(path)) #it is safe to push the old value to the stack since chdir was successful
    
def popd():
    os.chdir(dirStack[-1])
    dirStack.pop() #it is safe to pop since chdir and access to last element in the stack was successful

deimos_base = os.environ['DEIMOS_BASE']

if deimos_base == "":
    print "DEIMOS_BASE is undefined"
    exit(1)

KRTD=join(deimos_base, "lib/krt")

SRCD= {
                                        
    join(deimos_base, "lib/Bkup/newlib-src/newlib/libc") : {"prefix" : ""},
    join(deimos_base, "lib/Bkup/newlib-src/newlib/libm") : {"prefix" : ""},
    "/home/sandeepd2/Source/osdev/gcc/build-gcc/gcc/include/" : {"prefix" : "include" }
}



def getTargetDir(filePath):
    print "filePath:", filePath
    for d in SRCD.keys():
        if filePath.startswith(d):
            prefix = SRCD[d]["prefix"]
            relPath = join(prefix, filePath[len(d)+1:])
            return os.path.dirname(join(KRTD, relPath))

def run(*cmd):
    l=[]
    for i, x in enumerate(cmd):
        if i == 0:
            l.extend(str(x).split())
        else:
            l.append(x)
    
    return subprocess.Popen(l, stdout=subprocess.PIPE, stderr=subprocess.STDOUT).communicate()[0].split("\n")


def getMissingFiles():
    regexMissingFile = re.compile(".*fatal error: (.*): No such file or directory")
    missingFiles = []
    pushd(deimos_base)
    for line in run("scons"):
        m = regexMissingFile.match(line)
        
        if m is not None:
            print "Make file error:", line
            missingFiles.append(m.groups()[0])
    
    popd()
    return missingFiles
    


while True:
    #print "Entering:", KRTD
    pushd(KRTD)

    #Create a list of missing files
    missingFiles = getMissingFiles()

    if len(missingFiles) == 0:
        break
        
    print "Missing files: ", missingFiles

    #print "Entering:", NLD

    files = []
    for d in SRCD.keys():
        files.extend(run("find " + d))

    #print files

    chosenSubst = {}

    for mf in missingFiles:
        subst = files | grep("/"+ mf + "$") | tuple
        
        
        if len(subst) == 0:
            print "ERROR: could not find file - ", "/"+ mf + "$"
            continue
        
        if(len(subst) > 1):
            print "Please choose substitute file from :-"
            for i, s in enumerate(subst):
                print i+1, ". ", s
            
            inp = int(raw_input())
            chosenSubst[mf] = subst[inp - 1]
        else:
            chosenSubst[mf] = subst[0]

    for orig, subst in chosenSubst.items():
        #print "shutil.copytree("+os.path.join(NLD , subst)+", "+KRTD+")"
        #src=os.path.join(NLD , subst)
        
        destDir = getTargetDir(subst)
        
        print "destDir:", destDir
        
        if not os.path.exists(destDir):
            print "Making dir: ", destDir
            os.makedirs(destDir)
        
        print "Copying file: %s to %s" % (subst, destDir) 
        shutil.copy(subst, destDir)
    
    print ""

print "Done!"
