#NOTE: librt.a is required for clock_getres() and clock_gettime
#TODO: remove references to librt.a and prevent linking to all standard libraries
#CFLAGS=-m32 -nostdlib -nostdinc -fno-builtin -fno-stack-protector -c -g
#CXXFLAGS=$(CFLAGS) -fno-rtti -fno-exceptions
#LDFLAGS=-melf_i386 --oformat=elf32-i386 -Tlink.ld -L../lib -L../lib/newlib/lib #Do not force scons to use ld instead of gcc
#LIBS=-lkruntime
env32 = Environment(CFLAGS='-m32', DFLAGS='-m32', LINKFLAGS='-m32', LIBS=['rt'])

objs = []
objs.extend(env32.Object(Glob("*.d")))
objs.extend(env32.Object(Glob("*.c")))
objs.extend(env32.Object(Glob("*.s")))

env32.Program("kernel", objs)
